api/urls.py
from django.urls import path
from api.views import BookReviewDetailAPIView, BookReviewAPIView

app_name = "api"

urlpatterns = [
    path('reviews/<int:id>/', BookReviewDetailAPIView.as_view(), name="review_detail"),
    path('reviews/', BookReviewAPIView.as_view(), name="review-list"),
]

bookreads/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bookreads import settings
from bookreads.views import landing_page, home_page

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home_page, name="home_page"),
    path("users/", include("users.urls")),
    path("books/", include("books.urls")),
    path("api/", include("api.urls")),
    path('admin/', admin.site.urls),
    
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from books.views import BookView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView

app_name = "books"

urlpatterns = [
    path('', BookView.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path('<int:id>/reviews/', AddReviewView.as_view(), name="reviews"),
    path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name="edit_review"),
    path('<int:book_id>/reviews/<int:review_id>/delete/confirm', ConfirmDeleteReviewView.as_view(), name="confirm_delete_review"),
    path('<int:book_id>/reviews/<int:review_id>/delete/', DeleteReviewView.as_view(), name="delete_review")
]

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('profile_edit/', ProfileUpdateView.as_view(), name="profile_edit")
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:profile_edit' as profile_edit_page_url  %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Bookreads{% endblock %}</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link href="{% static '/css/main.css' %}" rel="stylesheet" type="text/css">
</head>
<body class="mx-4">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3" >
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing_page' %}">Bookreads</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{{ home_page_url }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == books_page_url %} active {% endif %}" aria-current="page" href="{{ books_page_url }}">Books</a>
        </li>
      </ul>

          <div>
              {% if request.user.is_authenticated %}
                    <ul class="navbar-nav me-5" >
                          <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == profile_edit_page_url %} active {% endif %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    {{ request.user.username }}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{{ profile_page_url }}">profile</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                                </ul>
                          </li>
                    </ul>
              {% else %}
                    <a class="btn btn-info" href="{% url 'users:login' %}">Login</a>
              {% endif %}
          </div>
    </div>
  </div>
</nav>


<div class="container">
    {% if messages %}
         {% for message in messages %}
             <div class="mt-3">
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
             </div>
         {% endfor %}

    {% endif %}
</div>


{% block content %}{% endblock %}

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}

{% block content %}
<h3>Home page</h3>
    {% for review in page_obj %}
        <div class="container post-content">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="media mb-3">
                                <img src="{{ review.user.profile.url }}" class="d-block ui-w-40 rounded-circle" alt="">
                                <div class="media-body ml-3">
                                    <b>{{ review.user.username }}</b> rated this book {{ review.stars_given }} stars
                                    <div class="text-muted small">{{ review.created_at | date:"M d, Y" }} </div>
                                </div>
                            </div>
                            <p>
                               {{ review.comment | truncatechars:300 }}
                            </p>
                            <img class="cover-pic center" src="{{ review.book.cover_picture.url }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
<nav>
        <ul class="pagination">
             {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                <li class="page-item"><a class="page-link" href="?page{{ page_obj.previous_page_number }}">previous</a></li>
             {% endif %}
             <li class="page-item active">
                  <a href="#" class="page-link">{{ page_obj.number }}</a>
             </li>
             {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                <li class="page-item"><a class="page-link" href="?page{{ page_obj.paginator.num_pages }}">previous</a></li>
             {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Landing Page</h1>

    <p>This group is just for people who love books such as The Hunger Games, Divergent, Harry Potter,
        Percy Jackson ,and more! Have fun reading and discussing books with the other members and
        voting on polls.Set in the nineteenth century, World Odyssey (The World Duology, #1) follows
        the fortunes of three young travelers as each embarks on an epic journey. Their dramatic adventures
        span sixteen years and see them engage with Native American Indians, Barbary Coast pirates, Aborigines,
        Maoris and Pacific Islanders as they travel around the world – from America to Africa, from England to the
        Canary Islands, to Australia, New Zealand and Samoa.
        Ambitious American adventurer Nathan Johnson’s journey begins when he runs away to sea to escape a violent
        father. After surviving a shipwreck and enslavement by one of the indigenous tribes of America’s northwest,
        his stocks rise and he becomes a successful trader. When Nathan decides to visit Fiji to trade muskets to the natives,
        he doesn’t know it but his fortunes are about to change again.
    </p>

{% endblock %}