api/urls.py
from django.urls import path
from api.views import BookReviewDetailAPIView, BookReviewAPIView

app_name = "api"

urlpatterns = [
    path('reviews/<int:id>/', BookReviewDetailAPIView.as_view(), name="review_detail"),
    path('reviews/', BookReviewAPIView.as_view(), name="review-list"),
]

bookreads/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bookreads import settings
from bookreads.views import landing_page, home_page

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home_page, name="home_page"),
    path("users/", include("users.urls")),
    path("books/", include("books.urls")),
    path("api/", include("api.urls")),
    path('admin/', admin.site.urls),
    
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from books.views import BookView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView

app_name = "books"

urlpatterns = [
    path('', BookView.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path('<int:id>/reviews/', AddReviewView.as_view(), name="reviews"),
    path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name="edit_review"),
    path('<int:book_id>/reviews/<int:review_id>/delete/confirm', ConfirmDeleteReviewView.as_view(), name="confirm_delete_review"),
    path('<int:book_id>/reviews/<int:review_id>/delete/', DeleteReviewView.as_view(), name="delete_review")
]

books/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from users.models import CustomUser


class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default="default_cover.jpg")

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.book.title} by {self.author.first_name} {self.author.last_name}"


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.stars_given} stars for {self.book.title} by {self.user.username}"

books/forms.py
from django import forms
from books.models import BookReview


class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = BookReview
        fields = ('stars_given', 'comment')

books/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView

from books.forms import BookReviewForm
from books.models import Book, BookReview


class BookView(View):
    def get(self, request):
        books = Book.objects.all().order_by("id")
        search_query = request.GET.get('q', '')
        if search_query:
            books = books.filter(title__icontains=search_query)
        paginator = Paginator(books, 2)
        page_num = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_num)

        return render(request, "books/list.html", {"page_obj": page_obj, "search_query": search_query})


class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm()
        return render(request, "books/detail.html", {"book": book, "review_form": review_form})


class AddReviewView(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm(data=request.POST)

        if review_form.is_valid():
            BookReview.objects.create(
                book=book,
                user=request.user,
                stars_given=review_form.cleaned_data['stars_given'],
                comment=review_form.cleaned_data['comment']
            )
            return redirect(reverse("books:detail", kwargs={"id": book.id}))
        return render(request, "books/detail.html", {"book": book, "review_form": review_form})


class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_from = BookReviewForm(instance=review)
        return render(request, "books/edit_review.html", {"book": book, "review": review, "review_from": review_from})

    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_from = BookReviewForm(instance=review, data=request.POST)

        if review_from.is_valid():
            review_from.save()
            return redirect(reverse("books:detail", kwargs={"id": book.id}))
        return render(request, "books/edit_review.html", {"book": book, "review": review, "review_from": review_from})


class ConfirmDeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        return render(request, 'books/confirm_delete_review.html', {"book": book, "review": review})


class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)

        review.delete()
        messages.success(request, "You have successfully deleted this review")
        return redirect(reverse("books:detail", kwargs={"id": book.id}))

books/templates/books/confirm_delete_review.html
{% extends 'base.html' %}
{% block title %} Delete page {% endblock %}
{% block content %}
<h3>Are you sure you want to delete this review?</h3>

<p>
    <b>Book:</b> {{ book.title }}
</p>
<p>
    <b>Comment:</b> {{ review.comment }}
</p>
<a href="{% url 'books:delete_review' book.id review.id %}" class="btn btn-outline-danger">Yes</a>  <a href="{% url 'books:detail' book.id %}" class="btn btn-outline-primary">No</a>
{% endblock %}

books/templates/books/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Book Detail Page{% endblock %}}
{% block content %}
    <h1>Book Detail</h1>
<div class="row mb-4">
    <div class="col-2">
        <img alt="cover image" src="{{ book.cover_picture.url }}" width="200" height="250">
    </div>
    <div class="col-6 ms-6">
          <h3>{{ book.title }}</h3>
          <span class="fst-italic">
              Autored by
              {% for book_author in book.bookauthor_set.all %}
                 {% if forloop.last %}
                    {{ book_author.author.full_name }}
                 {% else %}
                    {{ book_author.author.full_name }},
                 {% endif %}
              {% endfor %}
          </span>
          <p>
                {{ book.description }}
          </p>
    </div>

</div>
<div class="row mb-4 ">
    <div class="col-6">
        <form method="post" action="{% url 'books:reviews' book.id %}">
            {% csrf_token %}
            {{ review_form | crispy }}
            <button class="btn btn-success">Add Review</button>
        </form>

    </div>
</div>

{% if book.bookreview_set.exists %}
    <h4>Reviews</h4>  <hr>

    {% for review in book.bookreview_set.all %}
        <div class="row mb-3">
            <div class="col-1 me-2">
                <img class="small-profile-pic" src="{{ review.user.profile_picture.url }}" height="100" width="100">
            </div>
            <div class="col-7">
                <b>{{ review.user.username }}</b> rated it {{ review.stars_given }} stars <span class="fw-lighter">{{ review.created_at }}</span>
                {% if review.user == request.user %}
                    <a href="{% url 'books:edit_review' book.id review.id %}"><i class="bi bi-pen"></i></a>
                    <a href="{% url 'books:confirm_delete_review' book.id review.id %}"><i class="bi bi-trash"></i></a>
                {% endif %}
                <p class="mt-2 font-monospase fs-6">{{ review.comment}}</p>
            </div>
        </div>
    {% endfor %}
{% endif %}



{% endblock %}

books/templates/books/edit_review.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Edit review {% endblock %}

{% block content %}
    <h3>Edit review</h3>
    <div class="row mb-5 ">
        <div class="col-6">
            <form method="post" action="{% url 'books:edit_review' book.id review.id %}">
                {% csrf_token %}
                {{ review_form | crispy }}
            <button class="btn btn-success">Save</button>
            </form>


        </div>
    </div>

{% endblock %}

books/templates/books/list.html
{% extends "base.html" %}

{% block title %}Books Page{% endblock %}

{% block content %}
<h1>Books</h1>
<div class="row mb-3">
    <div class="col-4">
        <form class="d-flex" method="get">
            <input class="form-control me-2" type="text" placeholder="Search" name="q" value="{{ search_query }}">
            <button class="btn btn-success">Search</button>
        </form>
    </div>
</div>


{% if page_obj %}

        {% for book in page_obj.object_list %}
            <div class="row mb-4">
                <div class="col-2">
                    <img src="{{ book.cover_picture.url }}" width="200" height="250">
                </div>
                <div class="col-6 ms-6">
                    <a href="{% url 'books:detail' book.id %}">{{ book.title }}</a>
                    <p>
                        {{ book.description }}
                    </p>
                </div>

            </div>

        {% endfor %}
    <nav>
        <ul class="pagination">
             {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                <li class="page-item"><a class="page-link" href="?page{{ page_obj.previous_page_number }}">previous</a></li>
             {% endif %}
             <li class="page-item active">
                  <a href="#" class="page-link">{{ page_obj.number }}</a>
             </li>
             {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                <li class="page-item"><a class="page-link" href="?page{{ page_obj.paginator.num_pages }}">previous</a></li>
             {% endif %}
        </ul>
    </nav>

{% else %}
   No books found.
{% endif %}
{% endblock %}